INSERT INTO
    `accounts_city` (`name`, `created_at`, `updated_at`, `state_id`)
VALUES
    (
        'Los Angeles',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'California'
        )
    ),
    (
        'San Francisco',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'California'
        )
    ),
    (
        'San Diego',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'California'
        )
    ),
    (
        'San Jose',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'California'
        )
    ),
    (
        'Sacramento',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'California'
        )
    ),
    (
        'Houston',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Texas'
        )
    ),
    (
        'Dallas',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Texas'
        )
    ),
    (
        'Austin',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Texas'
        )
    ),
    (
        'San Antonio',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Texas'
        )
    ),
    (
        'Fort Worth',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Texas'
        )
    ),
    (
        'New York City',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'New York'
        )
    ),
    (
        'Buffalo',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'New York'
        )
    ),
    (
        'Rochester',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'New York'
        )
    ),
    (
        'Albany',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'New York'
        )
    ),
    (
        'Syracuse',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'New York'
        )
    ),
    (
        'Miami',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Florida'
        )
    ),
    (
        'Orlando',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Florida'
        )
    ),
    (
        'Tampa',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Florida'
        )
    ),
    (
        'Jacksonville',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Florida'
        )
    ),
    (
        'Fort Lauderdale',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Florida'
        )
    ),
    (
        'Chicago',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Illinois'
        )
    ),
    (
        'Aurora',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Illinois'
        )
    ),
    (
        'Naperville',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Illinois'
        )
    ),
    (
        'Springfield',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Illinois'
        )
    ),
    (
        'Philadelphia',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Pennsylvania'
        )
    ),
    (
        'Pittsburgh',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Pennsylvania'
        )
    ),
    (
        'Allentown',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Pennsylvania'
        )
    ),
    (
        'Erie',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Pennsylvania'
        )
    ),
    (
        'Peoria',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Illinois'
        )
    ),
    (
        'Harrisburg',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Pennsylvania'
        )
    ),
    (
        'Columbus',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Ohio'
        )
    ),
    (
        'Cleveland',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Ohio'
        )
    ),
    (
        'Cincinnati',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Ohio'
        )
    ),
    (
        'Toledo',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Ohio'
        )
    ),
    (
        'Akron',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Ohio'
        )
    ),
    (
        'Atlanta',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Georgia'
        )
    ),
    (
        'Savannah',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Georgia'
        )
    ),
    (
        'Augusta',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Georgia'
        )
    ),
    (
        'Macon',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Georgia'
        )
    ),
    (
        'Columbus',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Georgia'
        )
    ),
    (
        'Charlotte',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'North Carolina'
        )
    ),
    (
        'Raleigh',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'North Carolina'
        )
    ),
    (
        'Greensboro',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'North Carolina'
        )
    ),
    (
        'Durham',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'North Carolina'
        )
    ),
    (
        'Winston-Salem',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'North Carolina'
        )
    ),
    (
        'Detroit',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Michigan'
        )
    ),
    (
        'Grand Rapids',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Michigan'
        )
    ),
    (
        'Warren',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Michigan'
        )
    ),
    (
        'Ann Arbor',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Michigan'
        )
    ),
    (
        'Lansing',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Michigan'
        )
    ),
    (
        'Shinjuku',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Tokyo'
        )
    ),
    (
        'Shibuya',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Tokyo'
        )
    ),
    (
        'Akihabara',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Tokyo'
        )
    ),
    (
        'Ikebukuro',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Tokyo'
        )
    ),
    (
        'Ginza',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Tokyo'
        )
    ),
    (
        'Osaka City',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Osaka'
        )
    ),
    (
        'Namba',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Osaka'
        )
    ),
    (
        'Umeda',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Osaka'
        )
    ),
    (
        'Tennoji',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Osaka'
        )
    ),
    (
        'Sakai',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Osaka'
        )
    ),
    (
        'Kyoto City',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Kyoto'
        )
    ),
    (
        'Uji',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Kyoto'
        )
    ),
    (
        'Fushimi',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Kyoto'
        )
    ),
    (
        'Arashiyama',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Kyoto'
        )
    ),
    (
        'Kameoka',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Kyoto'
        )
    ),
    (
        'Sapporo',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Hokkaido'
        )
    ),
    (
        'Hakodate',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Hokkaido'
        )
    ),
    (
        'Asahikawa',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Hokkaido'
        )
    ),
    (
        'Obihiro',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Hokkaido'
        )
    ),
    (
        'Kushiro',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Hokkaido'
        )
    ),
    (
        'Fukuoka City',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Fukuoka'
        )
    ),
    (
        'Kitakyushu',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Fukuoka'
        )
    ),
    (
        'Kurume',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Fukuoka'
        )
    ),
    (
        'Omuta',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Fukuoka'
        )
    ),
    (
        'Iizuka',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Fukuoka'
        )
    ),
    (
        'Nagoya',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Aichi'
        )
    ),
    (
        'Toyota',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Aichi'
        )
    ),
    (
        'Okazaki',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Aichi'
        )
    ),
    (
        'Ichinomiya',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Aichi'
        )
    ),
    (
        'Toyohashi',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Aichi'
        )
    ),
    (
        'Yokohama',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Kanagawa'
        )
    ),
    (
        'Kawasaki',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Kanagawa'
        )
    ),
    (
        'Sagamihara',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Kanagawa'
        )
    ),
    (
        'Fujisawa',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Kanagawa'
        )
    ),
    (
        'Yokosuka',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Kanagawa'
        )
    ),
    (
        'Saitama City',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Saitama'
        )
    ),
    (
        'Kawaguchi',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Saitama'
        )
    ),
    (
        'Koshigaya',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Saitama'
        )
    ),
    (
        'Tokorozawa',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Saitama'
        )
    ),
    (
        'Kasukabe',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Saitama'
        )
    ),
    (
        'Kobe',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Hyogo'
        )
    ),
    (
        'Himeji',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Hyogo'
        )
    ),
    (
        'Nishinomiya',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Hyogo'
        )
    ),
    (
        'Amagasaki',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Hyogo'
        )
    ),
    (
        'Akashi',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Hyogo'
        )
    ),
    (
        'Hiroshima City',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Hiroshima'
        )
    ),
    (
        'Fukuyama',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Hiroshima'
        )
    ),
    (
        'Kure',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Hiroshima'
        )
    ),
    (
        'Onomichi',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Hiroshima'
        )
    ),
    (
        'Mihara',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Hiroshima'
        )
    ),
    (
        'Mumbai',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Maharashtra'
        )
    ),
    (
        'Pune',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Maharashtra'
        )
    ),
    (
        'Nagpur',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Maharashtra'
        )
    ),
    (
        'Nashik',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Maharashtra'
        )
    ),
    (
        'Aurangabad',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Maharashtra'
        )
    ),
    (
        'New Delhi',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Delhi'
        )
    ),
    (
        'South Delhi',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Delhi'
        )
    ),
    (
        'North Delhi',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Delhi'
        )
    ),
    (
        'West Delhi',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Delhi'
        )
    ),
    (
        'East Delhi',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Delhi'
        )
    ),
    (
        'Bangalore',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Karnataka'
        )
    ),
    (
        'Mysore',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Karnataka'
        )
    ),
    (
        'Mangalore',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Karnataka'
        )
    ),
    (
        'Hubli',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Karnataka'
        )
    ),
    (
        'Belgaum',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Karnataka'
        )
    ),
    (
        'Chennai',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Tamil Nadu'
        )
    ),
    (
        'Coimbatore',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Tamil Nadu'
        )
    ),
    (
        'Madurai',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Tamil Nadu'
        )
    ),
    (
        'Tiruchirappalli',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Tamil Nadu'
        )
    ),
    (
        'Salem',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Tamil Nadu'
        )
    ),
    (
        'Kolkata',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'West Bengal'
        )
    ),
    (
        'Howrah',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'West Bengal'
        )
    ),
    (
        'Durgapur',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'West Bengal'
        )
    ),
    (
        'Asansol',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'West Bengal'
        )
    ),
    (
        'Siliguri',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'West Bengal'
        )
    ),
    (
        'Lucknow',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Uttar Pradesh'
        )
    ),
    (
        'Kanpur',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Uttar Pradesh'
        )
    ),
    (
        'Varanasi',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Uttar Pradesh'
        )
    ),
    (
        'Agra',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Uttar Pradesh'
        )
    ),
    (
        'Meerut',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Uttar Pradesh'
        )
    ),
    (
        'Hyderabad',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Telangana'
        )
    ),
    (
        'Warangal',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Telangana'
        )
    ),
    (
        'Nizamabad',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Telangana'
        )
    ),
    (
        'Karimnagar',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Telangana'
        )
    ),
    (
        'Khammam',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Telangana'
        )
    ),
    (
        'Kochi',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Kerala'
        )
    ),
    (
        'Thiruvananthapuram',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Kerala'
        )
    ),
    (
        'Kozhikode',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Kerala'
        )
    ),
    (
        'Thrissur',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Kerala'
        )
    ),
    (
        'Kannur',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Kerala'
        )
    ),
    (
        'Ahmedabad',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Gujarat'
        )
    ),
    (
        'Surat',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Gujarat'
        )
    ),
    (
        'Vadodara',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Gujarat'
        )
    ),
    (
        'Rajkot',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Gujarat'
        )
    ),
    (
        'Bhavnagar',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Gujarat'
        )
    ),
    (
        'Ludhiana',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Punjab'
        )
    ),
    (
        'Amritsar',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Punjab'
        )
    ),
    (
        'Jalandhar',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Punjab'
        )
    ),
    (
        'Patiala',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Punjab'
        )
    ),
    (
        'Bathinda',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Punjab'
        )
    ),
    (
        'Gangnam',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Seoul'
        )
    ),
    (
        'Jongno',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Seoul'
        )
    ),
    (
        'Haeundae',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Busan'
        )
    ),
    (
        'Seomyeon',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Busan'
        )
    ),
    (
        'Bupyeong',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Incheon'
        )
    ),
    (
        'Songdo',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Incheon'
        )
    ),
    (
        'Jung-gu',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Daegu'
        )
    ),
    (
        'Dongseongro',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Daegu'
        )
    ),
    (
        'Yuseong',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Daejeon'
        )
    ),
    (
        'Seo-gu',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Daejeon'
        )
    ),
    (
        'Dong-gu',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Gwangju'
        )
    ),
    (
        'Nam-gu',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Gwangju'
        )
    ),
    (
        'Nam-gu',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Ulsan'
        )
    ),
    (
        'Jung-gu',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Ulsan'
        )
    ),
    (
        'Suwon',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Gyeonggi'
        )
    ),
    (
        'Seongnam',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Gyeonggi'
        )
    ),
    (
        'Chuncheon',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Gangwon'
        )
    ),
    (
        'Gangneung',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Gangwon'
        )
    ),
    (
        'Jeju City',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Jeju'
        )
    ),
    (
        'Seogwipo',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Jeju'
        )
    ),
    (
        'Toronto',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Ontario'
        )
    ),
    (
        'Ottawa',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Ontario'
        )
    ),
    (
        'Montreal',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Quebec'
        )
    ),
    (
        'Quebec City',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Quebec'
        )
    ),
    (
        'Vancouver',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'British Columbia'
        )
    ),
    (
        'Victoria',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'British Columbia'
        )
    ),
    (
        'Calgary',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Alberta'
        )
    ),
    (
        'Edmonton',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Alberta'
        )
    ),
    (
        'Winnipeg',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Manitoba'
        )
    ),
    (
        'Brandon',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Manitoba'
        )
    ),
    (
        'Mexico City',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Mexico City'
        )
    ),
    (
        'Iztapalapa',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Mexico City'
        )
    ),
    (
        'Guadalajara',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Jalisco'
        )
    ),
    (
        'Zapopan',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Jalisco'
        )
    ),
    (
        'Monterrey',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Nuevo León'
        )
    ),
    (
        'San Nicolás',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Nuevo León'
        )
    ),
    (
        'Puebla City',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Puebla'
        )
    ),
    (
        'Tehuacán',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Puebla'
        )
    ),
    (
        'Veracruz City',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Veracruz'
        )
    ),
    (
        'Xalapa',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Veracruz'
        )
    ),
    (
        'Milan',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Lombardy'
        )
    ),
    (
        'Bergamo',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Lombardy'
        )
    ),
    (
        'Rome',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Lazio'
        )
    ),
    (
        'Latina',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Lazio'
        )
    ),
    (
        'Naples',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Campania'
        )
    ),
    (
        'Salerno',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Campania'
        )
    ),
    (
        'Palermo',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Sicily'
        )
    ),
    (
        'Catania',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Sicily'
        )
    ),
    (
        'Venice',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Veneto'
        )
    ),
    (
        'Verona',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Veneto'
        )
    ),
    (
        'Madrid',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Madrid'
        )
    ),
    (
        'Alcobendas',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Madrid'
        )
    ),
    (
        'Barcelona',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Catalonia'
        )
    ),
    (
        'Girona',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Catalonia'
        )
    ),
    (
        'Seville',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Andalusia'
        )
    ),
    (
        'Malaga',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Andalusia'
        )
    ),
    (
        'Valencia',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Valencian Community'
        )
    ),
    (
        'Alicante',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Valencian Community'
        )
    ),
    (
        'Bilbao',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Basque Country'
        )
    ),
    (
        'San Sebastian',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Basque Country'
        )
    ),
    (
        'Sydney',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'New South Wales'
        )
    ),
    (
        'Newcastle',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'New South Wales'
        )
    ),
    (
        'Melbourne',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Victoria'
        )
    ),
    (
        'Geelong',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Victoria'
        )
    ),
    (
        'Brisbane',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Queensland'
        )
    ),
    (
        'Gold Coast',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Queensland'
        )
    ),
    (
        'Perth',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Western Australia'
        )
    ),
    (
        'Fremantle',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Western Australia'
        )
    ),
    (
        'Adelaide',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'South Australia'
        )
    ),
    (
        'Mount Gambier',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'South Australia'
        )
    ),
    (
        'Moscow',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Moscow'
        )
    ),
    (
        'Saint Petersburg',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Saint Petersburg'
        )
    ),
    (
        'Novosibirsk',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Novosibirsk'
        )
    ),
    (
        'Yekaterinburg',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Yekaterinburg'
        )
    ),
    (
        'Kazan',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Kazan'
        )
    ),
    (
        'Jakarta',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Jakarta'
        )
    ),
    (
        'Bandung',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'West Java'
        )
    ),
    (
        'Semarang',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Central Java'
        )
    ),
    (
        'Surabaya',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'East Java'
        )
    ),
    (
        'Denpasar',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Bali'
        )
    ),
    (
        'Bangkok',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Bangkok'
        )
    ),
    (
        'Chiang Mai',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Chiang Mai'
        )
    ),
    (
        'Phuket City',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Phuket'
        )
    ),
    (
        'Pattaya',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Pattaya'
        )
    ),
    (
        'Khon Kaen',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Khon Kaen'
        )
    ),
    (
        'Manila',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Metro Manila'
        )
    ),
    (
        'Cebu City',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Cebu'
        )
    ),
    (
        'Davao City',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Davao'
        )
    ),
    (
        'Iloilo City',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Iloilo'
        )
    ),
    (
        'Baguio City',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Baguio'
        )
    ),
    (
        'Ho Chi Minh City',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Ho Chi Minh City'
        )
    ),
    (
        'Hanoi',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Hanoi'
        )
    ),
    (
        'Da Nang',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Da Nang'
        )
    ),
    (
        'Hai Phong',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Hai Phong'
        )
    ),
    (
        'Can Tho',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Can Tho'
        )
    ),
    (
        'Istanbul',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Istanbul'
        )
    ),
    (
        'Ankara',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Ankara'
        )
    ),
    (
        'Izmir',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Izmir'
        )
    ),
    (
        'Bursa',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Bursa'
        )
    ),
    (
        'Antalya',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Antalya'
        )
    ),
    (
        'Buenos Aires',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Buenos Aires'
        )
    ),
    (
        'Córdoba',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Córdoba'
        )
    ),
    (
        'Rosario',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Rosario'
        )
    ),
    (
        'Mendoza',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Mendoza'
        )
    ),
    (
        'San Miguel de Tucumán',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'San Miguel de Tucumán'
        )
    ),
    (
        'Riyadh',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Riyadh'
        )
    ),
    (
        'Jeddah',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Jeddah'
        )
    ),
    (
        'Mecca',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Mecca'
        )
    ),
    (
        'Medina',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Medina'
        )
    ),
    (
        'Dammam',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Dammam'
        )
    ),
    (
        'Dubai',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Dubai'
        )
    ),
    (
        'Abu Dhabi',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Abu Dhabi'
        )
    ),
    (
        'Sharjah',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Sharjah'
        )
    ),
    (
        'Ajman',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Ajman'
        )
    ),
    (
        'Ras Al Khaimah',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Ras Al Khaimah'
        )
    ),
    (
        'Johannesburg',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Gauteng'
        )
    ),
    (
        'Cape Town',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Western Cape'
        )
    ),
    (
        'Durban',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'KwaZulu-Natal'
        )
    ),
    (
        'Port Elizabeth',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Eastern Cape'
        )
    ),
    (
        'Bloemfontein',
        NOW(),
        NOW(),
        (
            SELECT
                id
            FROM
                accounts_state
            WHERE
                name = 'Free State'
        )
    );