INSERT INTO
    movies_language (name, created_at, updated_at)
VALUES
    ('English', NOW(), NOW()),
    ('Spanish', NOW(), NOW()),
    ('Japanese', NOW(), NOW()),
    ('Hindi', NOW(), NOW()),
    ('Tamil', NOW(), NOW()),
    ('Telugu', NOW(), NOW()),
    ('Malayalam', NOW(), NOW()),
    ('Kannada', NOW(), NOW()),
    ('Bengali', NOW(), NOW()),
    ('Marathi', NOW(), NOW()),
    ('Punjabi', NOW(), NOW()),
    ('Gujarati', NOW(), NOW()),
    ('Korean', NOW(), NOW()),
    ('Chinese (Mandarin)', NOW(), NOW()),
    ('Chinese (Cantonese)', NOW(), NOW()),
    ('French', NOW(), NOW()),
    ('German', NOW(), NOW()),
    ('Portuguese', NOW(), NOW()),
    ('Italian', NOW(), NOW()),
    ('Catalan', NOW(), NOW()),
    ('Russian', NOW(), NOW()),
    ('Indonesian', NOW(), NOW()),
    ('Javanese', NOW(), NOW()),
    ('Thai', NOW(), NOW()),
    ('Filipino', NOW(), NOW()),
    ('Cebuano', NOW(), NOW()),
    ('Malay', NOW(), NOW()),
    ('Vietnamese', NOW(), NOW()),
    ('Turkish', NOW(), NOW()),
    ('Arabic', NOW(), NOW()),
    ('Afrikaans', NOW(), NOW()),
    ('Zulu', NOW(), NOW()),
    ('Xhosa', NOW(), NOW());